version: 2
sources:
  - name: raw_data
    schema: '{{ var ("source_dataset_name") }}'
    tables:
      - name: _dlt_loads
      - name: pull_requests
      - name: issues
      - name: pull_requests__comments
      - name: pull_requests__comments__reactions
      - name: pull_requests__reactions
      - name: issues__comments
      - name: issues__comments__reactions
      - name: issues__reactions
  - name: transformed_data
    schema: '{{ var ("destination_dataset_name") }}'
    tables:
      - name: dlt_processed_load_ids

models:
      - name: dlt_processed_load_ids
        description: "This table contains all processed load ids for incremental loading"
      - name: _dlt_loads
        description: "Created by DLT. Tracks completed loads"
        columns:
          - name: load_id
            tests:
              - not_null
          - name: schema_name
          - name: status
            tests:
              - not_null
          - name: inserted_at
            tests:
              - not_null
          - name: schema_version_hash
      - name: pull_requests
        columns:
          - name: number
          - name: url
          - name: title
          - name: body
          - name: author__login
          - name: author__avatar_url
          - name: author__url
          - name: author_association
          - name: closed
          - name: closed_at
          - name: created_at
          - name: state
          - name: updated_at
          - name: reactions_total_count
          - name: comments_total_count
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: issues
        columns:
          - name: number
          - name: url
          - name: title
          - name: body
          - name: author__login
          - name: author__avatar_url
          - name: author__url
          - name: author_association
          - name: closed
          - name: created_at
          - name: state
          - name: updated_at
          - name: reactions_total_count
          - name: comments_total_count
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: closed_at
      - name: pull_requests__comments
        columns:
          - name: id
          - name: url
          - name: body
          - name: author__avatar_url
          - name: author__login
          - name: author__url
          - name: author_association
          - name: created_at
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: reactions_total_count
      - name: pull_requests__comments__reactions
        columns:
          - name: user__login
          - name: user__avatar_url
          - name: user__url
          - name: content
          - name: created_at
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: pull_requests__reactions
        columns:
          - name: user__login
          - name: user__avatar_url
          - name: user__url
          - name: content
          - name: created_at
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: issues__comments
        columns:
          - name: id
          - name: url
          - name: body
          - name: author__avatar_url
          - name: author__login
          - name: author__url
          - name: author_association
          - name: created_at
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: reactions_total_count
      - name: issues__comments__reactions
        columns:
          - name: user__login
          - name: user__avatar_url
          - name: user__url
          - name: content
          - name: created_at
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: issues__reactions
        columns:
          - name: user__login
          - name: user__avatar_url
          - name: user__url
          - name: content
          - name: created_at
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique